baseURL: https://0sn.net/
languageCode: ja-jp
title: minetaro12
theme: hugo-osan-theme
copyright: "&copy; 2021-2023 minetaro12"
paginate: 10

menu:
  header:
    - name: About
      weight: 1
      url: /about

    - name: Archives
      weight: 2
      url: /archives

    - name: Tags
      weight: 3
      url: /tags

    - name: Links
      weight: 4
      url: /links

    - name: Search
      weight: 5
      url: /search

    - name: My GitHub
      weight: 6
      url: https://github.com/minetaro12
      params:
        newtab: true

params:
  showsource: true
  contenturl: https://github.com/minetaro12/0sn.net/tree/master/content/
  description: Oさんのページ
  favicon: favicon.ico
  image: img/defogp.png
  postnav: false

markup:
  highlight:
    guessSyntax: true
    style: monokai #see https://xyproto.github.io/splash/docs/all.html
