baseurl = "https://new.minetaro12.com/"
languageCode = "ja-JP"
theme = "terminal"
paginate = 5
enableGitInfo = true

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  favicon = "favicon.ico"
  showLastUpdated = true

[languages]
  [languages.en]
    title = "minetaro12"
    subtitle = "Oさん"
    keywords = ""
    copyright = "&copy;2021 minetaro12"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "MINETARO12"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "links"
        name = "Links"
        url = "/links"

      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
