baseurl = "https://0sn.net/"
languageCode = "ja-jp"
theme = "terminal"
paginate = 4
enableGitInfo = true
#disqusShortname = "minetaro12"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 6
  fullWidthTheme = false
  centerTheme = true
  favicon = "favicon.ico"
  showLastUpdated = true

[languages]
  [languages.en]
    title = "minetaro12"
    subtitle = "Oさん"
    keywords = ""
    copyright = "&copy; 2021-2022 minetaro12"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "[minetaro12@osan]#"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "github"
        name = "My Github"
        url = "https://github.com/minetaro12"

      [[languages.en.menu.main]]
        identifier = "misskey"
        name = "My Misskey"
        url = "https://msk.minetaro12.com/@minetaro12"

      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "My Twitter"
        url = "https://twitter.com/1osan_x"

      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"

      [[languages.en.menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives"

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 2

[taxonomies]
	archives = "archives"
	tags = "tags"
